parameters:
    whosthere.bundle.listener.class: LpDigital\Bundle\WhosThereBundle\Listener\WhosThereListener

services:
    whosthere.bundle.listener:
        class: %whosthere.bundle.listener.class%
        arguments: ["@bundle.whosthere"]
